repos:
  - repo: local
    hooks:
      - id: debug-statements
        name: ğŸ› debug
        entry: poetry run debug-statement-hook
        language: system
        types: [python]
        stages: [commit]

      - id: trailing-whitespace
        name: âœ‚ï¸ trailing-whitespace
        entry: poetry run trailing-whitespace-fixer
        language: system
        types_or: [dotenv, gitignore, makefile, markdown, plain-text, python, sh, terraform, text, toml, yaml]
        stages: [commit]

      - id: end-of-file-fixer
        name: â›”ï¸ end-of-file-fixer
        entry: poetry run end-of-file-fixer
        exclude: ^source_data/
        language: system
        types_or: [dotenv, gitignore, makefile, markdown, plain-text, python, sh, terraform, text, toml, yaml]
        stages: [commit]

      - id: detect-aws-credentials
        name: â˜ï¸â€‹ detect-aws-credentials
        entry: poetry run detect-aws-credentials
        language: system
        types_or: [dotenv, gitignore, makefile, markdown, plain-text, python, sh, terraform, text, toml, yaml]
        stages: [commit]

      - id: check-yaml
        name: ğŸ•µï¸â€â™‚ï¸â€‹ check-yaml
        entry: poetry run check-yaml
        language: system
        types: [yaml]
        stages: [commit]

      - id: black
        name: â™Ÿï¸ black
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]

      - id: mypy
        name: ğŸ† mypy
        entry: poetry run mypy
        args: [--config-file, mypy.ini]
        language: system
        types: [python]
        stages: [commit]

      - id: ruff
        name: ğŸŒŸ ruff
        entry: poetry run ruff check
        language: system
        types: [python]
        stages: [commit]

      - id: interrogate
        name: ğŸ” interrogate
        entry: poetry run interrogate
        language: system
        types: [python]
        stages: [commit]
